# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.9.210202.1

import typing, winrt

_ns_module = winrt._import_ns_module("Windows.System.Display")

DisplayRequest = _ns_module.DisplayRequest
